# Cloudflare Tunnel Configuration
tunnel: homelab
credentials-file: /home/ishaf/traefik/cloudflared/0196190e-5e34-4ef0-bfa4-433be669da84.json
origincert: /home/ishaf/traefik/cloudflared/cert.pem

# Ingress rules - traffic routing
ingress:
  # Route external traffic through Traefik (port 80)
  - hostname: jellyfin.groundcraft.xyz
    service: http://192.168.0.102:80
    originRequest:
      httpHostHeader: jellyfin.groundcraft.xyz
      
  - hostname: qbit.groundcraft.xyz
    service: http://192.168.0.102:80
    originRequest:
      httpHostHeader: qbit.groundcraft.xyz
      
  - hostname: traefik.groundcraft.xyz
    service: http://192.168.0.102:8080
    originRequest:
      httpHostHeader: traefik.groundcraft.xyz
      
  # Catch-all rule (required - must be last)
  - service: http_status:404

# Optional: Tunnel configuration
warp-routing:
  enabled: false

# Optional: Metrics and logging
metrics: 0.0.0.0:2000
loglevel: info

# Optional: No TLS verification for local services
no-tls-verify: true
