# Cloudflare Tunnel Configuration
# Replace 'your-tunnel-name' with your actual tunnel name
# Replace 'your-tunnel-id.json' with your actual tunnel credentials file
tunnel: your-tunnel-name
credentials-file: /root/.cloudflared/your-tunnel-id.json

# Ingress rules - traffic routing
ingress:
  # Route external traffic to your services
  - hostname: jellyfin.yourdomain.com
    service: http://jellyfin:8096
    originRequest:
      httpHostHeader: jellyfin.yourdomain.com
      
  - hostname: qbit.yourdomain.com
    service: http://qbittorrent:8080
    originRequest:
      httpHostHeader: qbit.yourdomain.com
      
  - hostname: traefik.yourdomain.com
    service: http://traefik:8080
    originRequest:
      httpHostHeader: traefik.yourdomain.com
      
  # Catch-all rule (required - must be last)
  - service: http_status:404

# Optional: Tunnel configuration
warp-routing:
  enabled: false

# Optional: Metrics and logging
metrics: 0.0.0.0:2000
loglevel: info

# Optional: No TLS verification for local services
no-tls-verify: true
