version: "3.8"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - traefik_net
    dns:
      - 8.8.8.8  # Set a public DNS (Google's DNS in this case)
      - 8.8.4.4  # Backup public DNS
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/sdb2/radarr:/config
      - /mnt/sdb2/qbittorrent/downloads:/downloads
      - /mnt/sdb2/jellyfin/media/tv:/data/tvshows
      - /mnt/sdb2/jellyfin/media/movies:/data/movies
    # ports:
    #   - "7878:7878"  # Removed - access only through Traefik
    labels:
      - "traefik.enable=true"
      
      # Local access
      - "traefik.http.routers.radarr.rule=Host(`radarr.local`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      
      # External access via Cloudflare tunnel (HTTP)
      - "traefik.http.routers.radarr-external.rule=Host(`radarr.groundcraft.xyz`)"
      - "traefik.http.routers.radarr-external.entrypoints=web"
      
      # External access via Cloudflare (HTTPS with certificates)
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.groundcraft.xyz`)"
      - "traefik.http.routers.radarr-secure.entrypoints=websecure"
      - "traefik.http.routers.radarr-secure.tls.certresolver=cloudflare"

networks:
  traefik_net:
    external: true
